version: "3.7"

services:
  django-project:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: django-project
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    networks:
      - django-project-net
  redis:
    image: redis:alpine
    hostname: redis
    networks:
      - django-project-net
    ports:
      - "6379:6379"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A django-project worker -l info"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - django-project
    restart: on-failure
    networks:
      - django-project-net
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A django-project beat -l info"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - celery-worker
    restart: on-failure
    networks:
      - django-project-net
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - django-project-net
networks:
  django-project-net:
